name = "cloudflare-worker-template"
main = "src/index.ts"
compatibility_date = "2022-07-06"

account_id = "0c8c22bdcd98c3dc6a35190650ef7906"
route = ""
zone_id = ""

kv_namespaces = []

[vars]
DUMMY_VAR = "DUMMY_VAR"

[env.prod]
account_id = "d684d0f34602a66c97de230566a2fa87"
workers_dev = false
route = "cloudflare-worker-template.sesamy.com/*"
zone_id = "b944b5871689ada6ce48e380968a06b5"